services:
  app:
    build:
      context: .
      dockerfile: Containerfile
      target: dev-backend
    environment:
      TZ: Asia/Tokyo
      GOFLAGS: "-buildvcs=false"
      ALLOW_ORIGINS: "http://localhost:8825"
      MMBOX_DB_FILE_PATH: /data/mmbox.db
      DEBUG: "true"
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - type: bind
        source: ./
        target: /go/app
      - type: bind
        source: ./.go
        target: /go
      - type: volume
        source: sqlite-data
        target: /data
        volume:
          nocopy: true

  webui:
    build:
      context: .
      dockerfile: Containerfile
      target: dev-webui
    environment:
      TZ: Asia/Tokyo
      MMBOX_API_BASE_URL: "http://localhost:8025"
    ports:
      - 8825:8825
    volumes:
      - type: bind
        source: ./
        target: /app

  sqliteweb:
    image: sqrt3/sqlite-web
    environment:
      SQLITE_DATABASE: mmbox.db
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: sqlite-data
        target: /data
        volume:
          nocopy: true

volumes:
  sqlite-data:
